export * from './temp-installation.service'
export * from './temp-sale.service'
export * from './temp-sale-detail.service'
export * from './temp-sale-comment.service'
export * from './temp-sale-document.service'
export * from './temp-sale-history.service'